
[functions.update-daily-stats]
enabled = true
verify_jwt = true
import_map = "./functions/update-daily-stats/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-daily-stats/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-daily-stats/*.html" ]

[functions.delete-old-posts]
enabled = true
verify_jwt = false
import_map = "./functions/delete-old-posts/deno.json"
entrypoint = "./functions/delete-old-posts/index.ts"